// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAcgKxdHqnMgOb1cR7wAWqXmvAiIm4wuc',
    appId: '1:1008990740929:web:0d66a3f197b16212340f40',
    messagingSenderId: '1008990740929',
    projectId: 'instagram-clonefirebase',
    authDomain: 'instagram-clonefirebase.firebaseapp.com',
    storageBucket: 'instagram-clonefirebase.appspot.com',
    measurementId: 'G-KWFS38LL65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNvzNMSCxlkXE8FBECqaututShSQ8nXXo',
    appId: '1:1008990740929:android:f9cce54779c4b199340f40',
    messagingSenderId: '1008990740929',
    projectId: 'instagram-clonefirebase',
    storageBucket: 'instagram-clonefirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt5DyeDa7vjr55sFqNfMN2pmwvqi2k1LQ',
    appId: '1:1008990740929:ios:95d9afc4e5b01e90340f40',
    messagingSenderId: '1008990740929',
    projectId: 'instagram-clonefirebase',
    storageBucket: 'instagram-clonefirebase.appspot.com',
    iosClientId: '1008990740929-089sv4r0f2mpbe2t14rh4fair5bduc9i.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt5DyeDa7vjr55sFqNfMN2pmwvqi2k1LQ',
    appId: '1:1008990740929:ios:95d9afc4e5b01e90340f40',
    messagingSenderId: '1008990740929',
    projectId: 'instagram-clonefirebase',
    storageBucket: 'instagram-clonefirebase.appspot.com',
    iosClientId: '1008990740929-089sv4r0f2mpbe2t14rh4fair5bduc9i.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
